name: Deploy Docs

on:
    workflow_dispatch:
    schedule:
        - cron: '0 3 * * *' # every day at 3 am UTC

jobs:
    deploy-nightly-demo-app:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout üõéÔ∏è
              uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'

            - uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - run: yarn install
            - run: npm run build
              working-directory: packages/dockview-core
            - run: npm run build
              working-directory: packages/dockview
            - run: npm run build
              working-directory: packages/docs
            - run: npm run docs
              working-directory: .
            - run: npm run package-docs
              working-directory: .
            - name: Deploy üöÄ
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: build # The folder the action should deploy.
                  TARGET_FOLDER: .
                  CLEAN: true # Automatically remove deleted files from the deploy branch
