name: Publish to npm

env:
    NPM_CONFIG_PROVENANCE: true
on:
    workflow_dispatch:
    release:
        types: [published]
jobs:
    publish:
        if: github.event_name == 'release'
        runs-on: ubuntu-latest
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'

            - uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - run: yarn
            - name: Publish dockview-core
              run: npm publish --provenance
              working-directory: packages/dockview-core
            - name: Publish dockview
              run: npm publish --provenance
              working-directory: packages/dockview
            - name: Publish dockview-vue
              run: npm publish --provenance
              working-directory: packages/dockview-vue
    publish-experimental:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'

            - uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - run: yarn
            - run: npm run set-experimental-versions
            - name: Publish dockview-core
              run: npm publish --provenance --tag experimental
              working-directory: packages/dockview-core
            - name: Publish dockview
              run: npm publish --provenance --tag experimental
              working-directory: packages/dockview
            - name: Publish dockview-vue
              run: npm publish --provenance --tag experimental
              working-directory: packages/dockview-vue
